### ISSUE TITLE
Analyzer error: No such var

### ISSUE THREAD

**Issue by plexus** [cljdoc/cljdoc#112] opened 2018-09-08 18:57 UTC
This code seems to cause problems to the analyzer, not sure why. Maybe it doesn't like periods in namespace aliases?

https://github.com/lambdaisland/kaocha/blob/b5c4c9c79df2c9c673a25e793faeaaa0411ff6fa/src/kaocha/load.clj#L9-L10

``` clojure
(def clj ctn.find/clj)
(def cljs ctn.find/cljs)
```

Build log: https://circleci.com/gh/martinklepsch/cljdoc-builder/4324

```
Caused by: java.lang.RuntimeException: No such var: ctn.find/clj
```

**Comment by plexus** [comment] 2018-09-08 19:09
Same problem in a different namespace now, so I guess those dotted aliases are indeed the problem. Shame, I quite like using them :)

https://circleci.com/gh/martinklepsch/cljdoc-builder/4326

**Comment by martinklepsch** [comment] 2018-09-09 09:49
This issue was actually caused by cljdoc loading a specific version of `org.clojure/tools.namespace` that was too old for kaocha to function. This has been fixed by allowing projects to specify newer versions of the required analysis deps: https://github.com/cljdoc/cljdoc/commit/422f4636167d3534a9b636faf3d5c2ca7fa04eeb

**Closed by martinklepsch** 2018-09-09 09:49 UTC
