### ISSUE TITLE
Avoid analysis of some required namespace

### ISSUE THREAD

**Issue by frozar** [cljdoc/cljdoc#380] opened 2020-03-17 01:49 UTC
Hi, I really new to cljdoc and really enthousiast about it.
I'm developing a clojurescript library which uses the npm package "roughjs". I'm using shadow-cljs to build it. To acces the javascript code, I import the npm lib as follow:
```clojure
(ns roughcljs.core
  (:require ["roughjs/bin/rough" :default rough]
            [roughcljs.utils :as utils]
            [hickory.core :as hickory]
            )
  )
```
You can check it out here:
https://github.com/frozar/roughcljs/blob/80a756e6483903939efa81739ccb456788238eb7/src/main/roughcljs/core.cljs#L1-L6

The `:default` keyword is a specificity of shadow-cljs and seems to not be supported by codox, so in my experimentation, I replace it by `:as` and make the tiny fixes to the code.
I would like to run cljdoc on my package so I use the docker image generously provided. I build the jar of my project, and install it locally. Than I use the docker to run the analysis of the .cljs file of my project and I get this error:
```
Execution error (ExceptionInfo) at cljs.analyzer/error (analyzer.cljc:756).
No such namespace: roughjs/bin/rough, could not locate roughjs_SLASH_bin_SLASH_rough.cljs, roughjs_SLASH_bin_SLASH_rough.cljc, or JavaScript source providing "roughjs/bin/rough" (Please check that namespaces with dashes use underscores in the ClojureScript file name) in file /tmp/cljdoc-frozar-roughcljs-0.1.1-SNAPSHOT6990170541669620385/contents/roughcljs/core.cljs
```

That's normal because the generated jar archieve doesn't contain the javascript files. To use my library, one has to specify it in its clojurescript dependancies and to install the npm dependancies with a command line like npm add roughjs.

My question is:
Is it possible to ask to cljdoc to not analyse some namespace? Particularly the javascript namespace.

**Comment by frozar** [comment] 2020-03-17 14:29
This issue is related to:
https://github.com/cljdoc/cljdoc-analyzer/issues/5

**Comment by martinklepsch** [comment] 2020-04-13 12:16
Maybe we should consider this a duplicate of #289?

**Comment by frozar** [comment] 2020-04-13 13:49
Yes, it's mostly a verbose duplicate of #289. And as I like that comment of @mfikes there, you can close this issue if you want.

**Closed** 2020-04-13 14:21 UTC
Labels: Analysis
