### ISSUE TITLE
Error when ingesting project "impl-src is not a relative path"

### ISSUE THREAD

**Issue by bhb** [cljdoc/cljdoc#97] opened 2018-08-14 01:23 UTC
Repro:

1. Get latest cljdoc (as of this writing, master is at 3366eb54517055224d9b60c6201b40ba72c89a38)
2. `./script/cljdoc run`
3. Clone expound `git clone git@github.com:bhb/expound.git`
4. In expound dir, `git checkout clj-doc`. The commit should be 71d00d8a7c09497d7c1c9d36b226e6454becee3a
5. In cljdoc dir, do `./script/cljdoc ingest -g /path/to/expound -p expound/expound -v 0.7.2-SNAPSHOT --jar ~/.m2/repository/expound/expound/0.7.2-SNAPSHOT/expound-0.7.2-SNAPSHOT.jar --pom ~/.m2/repository/expound/expound/0.7.2-SNAPSHOT/expound-0.7.2-SNAPSHOT.pom --rev clj-doc` (note you'll need to adjust the git path to refer to your local path)

Expected: The project should ingest locally, the local server should display latest docs as committed to "clj-doc" branch in expound.

Actual: I get the following error:

```
19:20:07.149 [main] WARN cljdoc.config - No known profile found in CLJDOC_PROFILE null
19:20:07.173 [main] WARN cljdoc.config - No known profile found in CLJDOC_PROFILE null
19:20:19.114 [main] WARN cljdoc.config - No known profile found in CLJDOC_PROFILE null
19:20:20.458 [main] WARN cljdoc.config - No known profile found in CLJDOC_PROFILE null
WARN [2018-08-13 19:20:20,727] main - cljdoc.config No known profile found in CLJDOC_PROFILE null
Unpacking /Users/ben/.m2/repository/expound/expound/0.7.2-SNAPSHOT/expound-0.7.2-SNAPSHOT.jar
Analyzing expound/expound clj - used dependencies:
{:deps {org.clojure/clojure #:mvn{:version "1.9.0"}, org.clojure/core.specs.alpha #:mvn{:version "0.1.24"}, expound/expound #:mvn{:version "0.7.2-SNAPSHOT"}, org.clojure/spec.alp
ha #:mvn{:version "0.1.143"}, metosin/spec-tools #:mvn{:version "0.6.1"}, figwheel-sidecar/figwheel-sidecar #:mvn{:version "0.5.15"}, com.gfredericks/test.chuck #:mvn{:version "0
.2.8"}, io.aviso/pretty #:mvn{:version "0.1.34"}, org.clojure/clojurescript #:mvn{:version "1.10.339"}, ring/ring-spec #:mvn{:version "0.0.4"}, org.clojure/tools.namespace #:mvn{
:version "0.2.11"}, org.onyxplatform/onyx-spec #:mvn{:version "0.12.7.0"}, pjstadig/humane-test-output #:mvn{:version "0.8.0"}, org.clojure/java.classpath #:mvn{:version "0.2.2"}
, binaryage/devtools #:mvn{:version "0.9.10"}, orchestra/orchestra #:mvn{:version "2017.11.12-1"}, com.cemerick/piggieback #:mvn{:version "0.2.2"}, bolth/bolth #:mvn{:version "0.
1.0"}, codox/codox {:exclusions [enlive hiccup org.pegdown/pegdown], :git/url "https://github.com/martinklepsch/codox", :sha "7059b20c344842643f64d6d7f90b97ab9012ad10", :deps/roo
t "codox/"}, org.clojure/test.check #:mvn{:version "0.10.0-alpha3"}, vvvvalvalval/scope-capture #:mvn{:version "0.1.4"}, ring/ring-core #:mvn{:version "1.6.3"}}}
exit-code 1 ---------------------------------------------------------------
stdout --------------------------------------------------------------------

---------------------------------------------------------------------------
stderr --------------------------------------------------------------------
Downloading: expound/expound/0.7.2-SNAPSHOT/expound-0.7.2-20180814.011857-4.pom from https://repo.clojars.org/
Downloading: org/clojure/clojure/maven-metadata.xml from https://repo1.maven.org/maven2/
Downloading: org/clojure/clojure/maven-metadata.xml from https://repo.clojars.org/
Downloading: expound/expound/0.7.2-SNAPSHOT/expound-0.7.2-20180814.011857-4.jar from https://repo.clojars.org/
Error building classpath. /var/folders/gm/p9fh4d3n5m11nnyjrsry1cm80000gq/T/cljdoc-expound-expound-0.7.2-SNAPSHOT2301171942486655366/impl-src is not a relative path         [9/38]
java.lang.IllegalArgumentException: /var/folders/gm/p9fh4d3n5m11nnyjrsry1cm80000gq/T/cljdoc-expound-expound-0.7.2-SNAPSHOT2301171942486655366/impl-src is not a relative path
        at clojure.java.io$as_relative_path.invokeStatic(io.clj:414)
        at clojure.java.io$file.invokeStatic(io.clj:426)
        at clojure.java.io$file.invoke(io.clj:418)
        at clojure.tools.deps.alpha.extensions.deps$eval980$fn__982$fn__984.invoke(deps.clj:29)                                                                                           at clojure.core$map$fn__5583$fn__5584.invoke(core.clj:2734)                                                                                                                       at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)                                                                                                                at clojure.core$transduce.invokeStatic(core.clj:6803)                                                                                                                             at clojure.core$into.invokeStatic(core.clj:6819)                                                                                                                                  at clojure.core$into.invoke(core.clj:6807)                                                                                                                                        at clojure.tools.deps.alpha.extensions.deps$eval980$fn__982.invoke(deps.clj:28)
        at clojure.lang.MultiFn.invoke(MultiFn.java:243)
        at clojure.tools.deps.alpha$lib_paths$fn__1050.invoke(alpha.clj:199)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__7839.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__7839.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6748)
        at clojure.core$reduce.invoke(core.clj:6730)
        at clojure.tools.deps.alpha$lib_paths.invokeStatic(alpha.clj:195)
        at clojure.tools.deps.alpha$lib_paths.invoke(alpha.clj:193)
        at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:225)
        at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:206)
        at clojure.tools.deps.alpha.script.make_classpath$create_classpath.invokeStatic(make_classpath.clj:59)
        at clojure.tools.deps.alpha.script.make_classpath$create_classpath.invoke(make_classpath.clj:52)
        at clojure.tools.deps.alpha.script.make_classpath$run.invokeStatic(make_classpath.clj:70)
        at clojure.tools.deps.alpha.script.make_classpath$run.invoke(make_classpath.clj:64)
        at clojure.tools.deps.alpha.script.make_classpath$_main.invokeStatic(make_classpath.clj:109)
        at clojure.tools.deps.alpha.script.make_classpath$_main.doInvoke(make_classpath.clj:84)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.main$main_opt.invokeStatic(main.clj:317)
        at clojure.main$main_opt.invoke(main.clj:313)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)

---------------------------------------------------------------------------
Analyzing expound/expound cljs - used dependencies:
{:deps {org.clojure/clojure #:mvn{:version "1.9.0"}, org.clojure/core.specs.alpha #:mvn{:version "0.1.24"}, expound/expound #:mvn{:version "0.7.2-SNAPSHOT"}, org.clojure/spec.alp
ha #:mvn{:version "0.1.143"}, metosin/spec-tools #:mvn{:version "0.6.1"}, figwheel-sidecar/figwheel-sidecar #:mvn{:version "0.5.15"}, com.gfredericks/test.chuck #:mvn{:version "0
.2.8"}, io.aviso/pretty #:mvn{:version "0.1.34"}, org.clojure/clojurescript #:mvn{:version "1.10.339"}, ring/ring-spec #:mvn{:version "0.0.4"}, org.clojure/tools.namespace #:mvn{
:version "0.2.11"}, org.onyxplatform/onyx-spec #:mvn{:version "0.12.7.0"}, pjstadig/humane-test-output #:mvn{:version "0.8.0"}, org.clojure/java.classpath #:mvn{:version "0.2.2"}
, binaryage/devtools #:mvn{:version "0.9.10"}, orchestra/orchestra #:mvn{:version "2017.11.12-1"}, com.cemerick/piggieback #:mvn{:version "0.2.2"}, bolth/bolth #:mvn{:version "0.
1.0"}, codox/codox {:exclusions [enlive hiccup org.pegdown/pegdown], :git/url "https://github.com/martinklepsch/codox", :sha "7059b20c344842643f64d6d7f90b97ab9012ad10", :deps/roo
t "codox/"}, org.clojure/test.check #:mvn{:version "0.10.0-alpha3"}, vvvvalvalval/scope-capture #:mvn{:version "0.1.4"}, ring/ring-core #:mvn{:version "1.6.3"}}}
exit-code 1 ---------------------------------------------------------------
stdout --------------------------------------------------------------------

---------------------------------------------------------------------------
stderr --------------------------------------------------------------------
Error building classpath. /var/folders/gm/p9fh4d3n5m11nnyjrsry1cm80000gq/T/cljdoc-expound-expound-0.7.2-SNAPSHOT2301171942486655366/impl-src is not a relative path
java.lang.IllegalArgumentException: /var/folders/gm/p9fh4d3n5m11nnyjrsry1cm80000gq/T/cljdoc-expound-expound-0.7.2-SNAPSHOT2301171942486655366/impl-src is not a relative path
        at clojure.java.io$as_relative_path.invokeStatic(io.clj:414)
        at clojure.java.io$file.invokeStatic(io.clj:426)
        at clojure.java.io$file.invoke(io.clj:418)
        at clojure.tools.deps.alpha.extensions.deps$eval980$fn__982$fn__984.invoke(deps.clj:29)
        at clojure.core$map$fn__5583$fn__5584.invoke(core.clj:2734)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
        at clojure.core$transduce.invokeStatic(core.clj:6803)
        at clojure.core$into.invokeStatic(core.clj:6819)
        at clojure.core$into.invoke(core.clj:6807)
        at clojure.tools.deps.alpha.extensions.deps$eval980$fn__982.invoke(deps.clj:28)
        at clojure.lang.MultiFn.invoke(MultiFn.java:243)
        at clojure.tools.deps.alpha$lib_paths$fn__1050.invoke(alpha.clj:199)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__7839.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__7839.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6748)
        at clojure.core$reduce.invoke(core.clj:6730)
        at clojure.tools.deps.alpha$lib_paths.invokeStatic(alpha.clj:195)
        at clojure.tools.deps.alpha$lib_paths.invoke(alpha.clj:193)
        at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:225)
        at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:206)
        at clojure.tools.deps.alpha.script.make_classpath$create_classpath.invokeStatic(make_classpath.clj:59)
        at clojure.tools.deps.alpha.script.make_classpath$create_classpath.invoke(make_classpath.clj:52)
        at clojure.tools.deps.alpha.script.make_classpath$run.invokeStatic(make_classpath.clj:70)
        at clojure.tools.deps.alpha.script.make_classpath$run.invoke(make_classpath.clj:64)
        at clojure.tools.deps.alpha.script.make_classpath$_main.invokeStatic(make_classpath.clj:109)
        at clojure.tools.deps.alpha.script.make_classpath$_main.doInvoke(make_classpath.clj:84)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.main$main_opt.invokeStatic(main.clj:317)
        at clojure.main$main_opt.invoke(main.clj:313)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)

---------------------------------------------------------------------------
** ERROR: **
JVM Exception: #error {
 :cause Analysis failed
 :via
 [{:type java.lang.Exception
   :message Analysis failed
   :at [cljdoc.analysis.runner$analyze_impl invokeStatic runner.clj 113]}]
 :trace
 [[cljdoc.analysis.runner$analyze_impl invokeStatic runner.clj 113]
  [cljdoc.analysis.runner$analyze_impl invoke runner.clj 66]
  [cljdoc.cli$build invokeStatic cli.clj 15]
  [cljdoc.cli$build invoke cli.clj 12]
  [cli_matic.core$invoke_subcmd invokeStatic core.clj 797]
  [cli_matic.core$invoke_subcmd invoke core.clj 785]
  [cli_matic.core$run_cmd_STAR_ invokeStatic core.clj 831]
  [cli_matic.core$run_cmd_STAR_ invoke core.clj 817]
  [cli_matic.core$run_cmd invokeStatic core.clj 841]
  [cli_matic.core$run_cmd invoke core.clj 833]
  [cljdoc.cli$_main invokeStatic cli.clj 70]
  [cljdoc.cli$_main doInvoke cli.clj 68]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 702]
  [clojure.core$apply invokeStatic core.clj 657]
  [clojure.main$main_opt invokeStatic main.clj 317]
  [clojure.main$main_opt invoke main.clj 313]
  [clojure.main$main invokeStatic main.clj 424]
  [clojure.main$main doInvoke main.clj 387]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 702]
  [clojure.main main main.java 37]]}
```

I am using MacOS and my homebrew clojure version is `1.9.0.391`.

**Comment by martinklepsch** [comment] 2018-08-14 04:03
Do you have a global `deps.edn` that could affect this in any way?

**Comment by martinklepsch** [comment] 2018-08-14 06:53
I just tried this locally and can't reproduce the error. The loaded dependencies seem to be the same and I'm running the same version of Clojure `1.9.0.391`. 

Can you try adding `-Srepro` to the `clojure` invocation linked below and running again?

https://github.com/cljdoc/cljdoc/blob/65f4ae93f36d82fcb4f24ab596295854bed6baaa/modules/analysis-runner/src/cljdoc/analysis/runner.clj#L88-L90

Sidenote: you don't need to `git checkout` the branch you pass as `--rev` to the ingest script.

**Comment by bhb** [comment] 2018-08-14 17:46
Good idea! I did indeed have a global `deps.edn` file which contained a dependency with a `:local/root` path. When I added `-Srepro` (as you suggested) or just commented out that dependency, and re-ran the ingest command, I no longer got the "impl-src is not a relative path" error.

> Sidenote: you don't need to git checkout the branch you pass as --rev to the ingest script.

As of cljdoc 65f4ae93f36d82fcb4f24ab596295854bed6baaa (and after adding the `-Srepro` option as you suggested), if I don't do a `git checkout` in Expound, I'll get this error:

```
INFO [2018-08-14 11:37:13,794] main - cljdoc.analysis.git Cloning Git repo /Users/ben/code/clojure/expound
** ERROR: **
JVM Exception: #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [org.eclipse.jgit.treewalk.TreeWalk addTree TreeWalk.java 803]}]
 :trace
 [[org.eclipse.jgit.treewalk.TreeWalk addTree TreeWalk.java 803]
  [sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
  [sun.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 62]                                                                                                    [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]                                                                                            [java.lang.reflect.Method invoke Method.java 483]
  [clojure.lang.Reflector invokeMatchingMethod Reflector.java 93]
  [clojure.lang.Reflector invokeInstanceMethod Reflector.java 28]
  [cljdoc.git_repo$ls_files invokeStatic git_repo.clj 140]
  [cljdoc.git_repo$ls_files invoke git_repo.clj 132]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.AFn applyTo AFn.java 144]
  [orchestra.spec.test$spec_checking_fn$fn__30224 doInvoke test.clj 123]
  [clojure.lang.RestFn invoke RestFn.java 421]
  [cljdoc.analysis.git$analyze_git_repo$fn__2785 invoke git.clj 29]
  [cljdoc.analysis.git$analyze_git_repo invokeStatic git.clj 17]
  [cljdoc.analysis.git$analyze_git_repo invoke git.clj 13]
  [cljdoc.server.ingest$ingest_git_BANG_ invokeStatic ingest.clj 39]
  [cljdoc.server.ingest$ingest_git_BANG_ invoke ingest.clj 36]                                                                                                                      [cljdoc.cli$build invokeStatic cli.clj 30]
  [cljdoc.cli$build invoke cli.clj 12]
  [cli_matic.core$invoke_subcmd invokeStatic core.clj 797]                                                                                                                          [cli_matic.core$invoke_subcmd invoke core.clj 785]
  [cli_matic.core$run_cmd_STAR_ invokeStatic core.clj 831]
  [cli_matic.core$run_cmd_STAR_ invoke core.clj 817]
  [cli_matic.core$run_cmd invokeStatic core.clj 841]
  [cli_matic.core$run_cmd invoke core.clj 833]
  [cljdoc.cli$_main invokeStatic cli.clj 70]
  [cljdoc.cli$_main doInvoke cli.clj 68]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 702]
  [clojure.core$apply invokeStatic core.clj 657]
  [clojure.main$main_opt invokeStatic main.clj 317]
  [clojure.main$main_opt invoke main.clj 313]
  [clojure.main$main invokeStatic main.clj 424]
  [clojure.main$main doInvoke main.clj 387]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 702]
  [clojure.main main main.java 37]]}
```

Doing `git checkout clj-doc` fixes the error for me.

Thanks for all your help!

**Comment by martinklepsch** [comment] 2018-08-14 19:13
> Good idea! I did indeed have a global deps.edn file which contained a dependency with a :local/root path.

Awesome, what kind of dependency was it? Would be great to know in case anyone else runs into similar issues at a later time.

> As of cljdoc 65f4ae9 (and after adding the -Srepro option as you suggested), if I don't do a git checkout in Expound, I'll get this error:

Ah, interesting & surprising, might take a look at that later.

In the meantime I'll close this issue as I think we've identified the cause for the problem. 
Feel free to reopen or leave additional comments obviously 🙂

**Closed by martinklepsch** 2018-08-14 19:13 UTC

**Comment by bhb** [comment] 2018-08-15 00:34
@martinklepsch The exact line was 

`repl-main {:local/root "/Users/ben/code/clojure/repl-main"}`

where repl-main is a clone of https://github.com/bhb/repl-main (that project is WIP and doesn't do anything interesting yet)

Would it make sense for the call to "clojure" in `runner.clj` to always include "-Srepro"? It would seem that isolating the script from any global deps would be a good thing, since otherwise you may be debugging incompatible versions, etc.
