### ISSUE TITLE
Just built docset for new version of spec, version info in readme seems out of date

### ISSUE THREAD

**Issue by aviflax** [cljdoc/cljdoc#84] opened 2018-07-23 19:23 UTC
The [built docset](https://cljdoc.xyz/d/org.clojure/spec.alpha/0.2.168/doc/readme) is version 0.2.168, and the readme includes:

> Latest stable release: 0.1.143

Which is wrong. I don’t know where this came from… the latest version of the readme in [the canonical repo](https://github.com/clojure/spec.alpha) says:

> Latest stable release: 0.2.168

**Comment by aviflax** [comment] 2018-07-23 19:41
The build was [#2361](https://cljdoc.xyz/builds/2361).

(Oddly, the build results page says “We could not find the git repository for your project…” but then _directly_ below that it shows the correct SCM URL as the spec GitHub repository!)

**Comment by martinklepsch** [comment] 2018-07-23 20:13
Those errors are a bit off at the moment, will fix them soon. The reason the old version is shown in the README is that the git commit that has the appropriate release tag points to a version of the file containing the old version, see: https://github.com/clojure/spec.alpha/tree/d3c1a3db83da711c1920f93f8a759276b0522abb 

Will close this as "working as intended" for now.

**Closed by martinklepsch** 2018-07-23 20:13 UTC
