### ISSUE TITLE
Give library author more control over doc publishing

### ISSUE THREAD

**Issue by ajoberstar** [cljdoc/cljdoc#304] opened 2019-05-29 02:15 UTC
Issues like  #303, #298, #275 bring up some difficulties of knowing the environment each project requires for analysis to complete. I've had a similar issue due to the need of leveraging the POM file for "provided" dependencies. While a common convention in Maven builds, carried over to some other tools (presumably Lein), Gradle chooses to not include "provided" dependencies in the POM.

Since each build system already knows the full environment/classpath needed for the project, would it make sense to provide an option for the library author to analyze/publish the docs themselves to cljdoc? This could be either an API call to cljdoc to publish or publishing another artifact alongside your library e.g. `mylib-1.2.3-cljdoc.jar`. 

I'm guessing the current approach was chosen explicitly to avoid needing library authors to do much to adopt cljdoc, making it easier (hopefully) to get broad adoption of docs being available in the site. So I can understand if this would be considered a won't fix.

However, I'm also wondering if it makes sense to provide this as an alternative to get around edge cases.

**Comment by martinklepsch** [comment] 2019-06-03 19:35
Thanks for the issue @ajoberstar and being a backer on open collective 🙂 

If I understand correctly you're suggesting for library authors to be able to upload the necessary information to cljdoc manually. As you've already pointed out this would defeat part of the purpose of cljdoc and potentially break a bunch of "promises" that cljdoc makes to it's users; mainly that documentation will always be updated automatically.

The Clojure/Script version issues are a clear bug in cljdoc that will be addressed and the JVM version issue affects only a small number of projects (still bad) and can be solved by adding some configuration or determining the JVM version as described in https://github.com/cljdoc/cljdoc/issues/275#issuecomment-462923266.

With that in mind I feel like allowing users to upload things themselves would fix some of the symptoms without addressing the root causes — which actually aren't too hard to fix (at least the Clojure version one).

**Comment by martinklepsch** [comment] 2019-06-03 19:36
I'll close this for now because there's nothing immediately actionable here but happy to keep the conversation going if you have further thoughts! Thanks again! 👍

**Closed by martinklepsch** 2019-06-03 19:36 UTC

**Comment by ajoberstar** [comment] 2019-06-04 00:12
Thanks for the response, and again completely understand keeping this out of scope. Depending on what you mean by "manual", I might not have described it well enough.

In the Java ecosystem, library authors often publish JavaDoc as a `*-javadoc.jar` or have part of their build process produce the documentation and upload it to a site.

So for cljdoc, I was wondering if we similarly could have a library's build process include producing the necessary doc analysis and upload it either directly to cljdoc or as a sibling artifact `*-cljdoc.jar` that cljdoc would later pick up.

Rationale would be that my build process knows which version of Java to run under, knows the full classpath, etc. Additionally, docs could be available immediately on release, instead of requiring someone to go to the page and click "build".

I think it's a tradeoff between requiring cljdoc to deal with edge cases on your side (due to incomplete/differing metadata) or having library authors include something in their process. Definitely understand the preference towards the former, if you have to choose one. And supporting both may not make sense.

As someone who supports (yet another) build system plugin (for Gradle), I sometimes worry that the projects that use git source directly will make too many assumptions about how the project is structured and thus box out less mainstream tools like Gradle.

The only Gradle-related pain-point I've seen so far is that "provided" dependencies don't quite exist in Gradle. There's an analogous concept of `compileOnly` dependencies, but Gradle chose not to publish them in the POM (by default, at least).
