### ISSUE TITLE
Pages are huge

### ISSUE THREAD

**Issue by geokon-gh** [cljdoc/cljdoc#343] opened 2019-08-18 14:47 UTC
I just opened:  https://cljdoc.org/d/net.mikera/core.matrix/0.62.0/api/clojure.core.matrix

It's 3 columns of text, no pictures and I'm getting a 23MB webpage. 
I think this is a bug..

**Comment by martinklepsch** [comment] 2019-08-20 17:07
Hey George, thanks for your concerns, that would indeed be a bit of a bummer 😅 

I can't reproduce the problem right now, can you maybe provide some additional information about how you diagnosed this?

**Comment by geokon-gh** [comment] 2019-08-21 09:33
Maybe this is normal behavior and not a bug

I poked around a bit more and I realize we're talking about different things. 

So I stumbled on this by accident b/c Firefox was eating a lot of memory on my machine and so I opened up the `about:performance` feature and I noticed the CLJDOC tab was abnormally high compared to everything else

To look into it I'm hitting `Shift` + `F5`. Then selecting the `Memory` Tab and clicking `Take snapshot`

I'm getting about 20MB normally and 10MB with NoScript

However, when I look at the network transfer I'm getting similar numbers to you
```
506.72 KB / 82.34 KB transferred
```

I don't get where the 20MB is coming from but at leas it's not 20MB transfers :)  Feel free to close the issue if you feel the memory usage is a non-issue

**Comment by martinklepsch** [comment] 2019-08-21 11:11
Ah that makes sense! 

I’ll close this issue for now but if 20MB is unusual I’m happy to reopen.

**Closed by martinklepsch** 2019-08-21 11:11 UTC
