### ISSUE TITLE
CURRENT doesn't always redirect to latest version?

### ISSUE THREAD

**Issue by danielcompton** [cljdoc/cljdoc#375] opened 2020-01-19 22:23 UTC
I opened 
https://cljdoc.org/d/clj-kondo/clj-kondo/CURRENT/api/clj-kondo.core and was redirected to 
[https://cljdoc.org/d/clj-kondo/clj-kondo/**2020.01.10**/api/clj-kondo.core](https://cljdoc.org/d/clj-kondo/clj-kondo/2020.01.10/api/clj-kondo.core). When the page loaded, I saw a newer version was available. Should I have been redirected to
[https://cljdoc.org/d/clj-kondo/clj-kondo/_2020.01.13_/api/clj-kondo.core](https://cljdoc.org/d/clj-kondo/clj-kondo/2020.01.13/api/clj-kondo.core)?

<img width="449" alt="Screenshot of Safari (20-01-20, 11-22-29 AM)" src="https://user-images.githubusercontent.com/811954/72689533-308e4a80-3b77-11ea-8652-7df813c83599.png">

**Comment by martinklepsch** [comment] 2020-04-13 12:11
Probably. I'm not sure why this happened, but I also can't reproduce it. Will close this for now. If someone has a reproducible case, please shout 🙂

**Closed by martinklepsch** 2020-04-13 12:11 UTC
