### ISSUE TITLE
API Analysis issues with Specter

### ISSUE THREAD

**Issue by marcomorain** [cljdoc/cljdoc#261] opened 2019-01-24 14:27 UTC
Thanks for clj-doc, I love using it 👌 

https://cljdoc.org/d/com.rpl/specter/1.1.2/doc/readme

> We couldn't find any namespaces in this artifact. Most often the reason for this is that the analysis failed or that the artifact has been mispackaged and does not contain any Clojure source files. The latter might be on purpose for uber-module style artifacts. Please open an issue and we'll be happy to look into it.

I believe that there should be namespace documentation present for specter? So I'm opening an issue :)

Thanks!

**Comment by martinklepsch** [comment] 2019-01-24 19:20
Hey Marc, nice to hear you're liking it 👍 

I stumbled upon this issue with specter before. Somehow analysis is failing as you can see in the [build logs](https://circleci.com/gh/cljdoc/builder/845).

This being the important bit:

```
Caused by: clojure.lang.ExceptionInfo: Unable to resolve var: coll? in this context at line 1449 
com/rpl/specter.cljc
```

**Comment by martinklepsch** [comment] 2019-01-28 11:54
Ok, hardcoded a change so that analysis for Specter is only ran on Clojure and not ClojureScript. This fixes analysis and makes the docs usable: https://cljdoc.org/d/com.rpl/specter/1.1.2/api/com.rpl.specter

Would still be nice to figure out why this issue above occurs...

**Comment by frozar** [comment] 2020-04-16 11:21
As I get this same issue with the new analyzer, cljdoc-analyzer, I create this demo repo that focus on the reason "why the analysis of specter in cljs mode fails":
https://github.com/frozar/cljdoc_specter_support

**Comment by frozar** [comment] 2020-04-22 06:51
To sum up the situation, this issue is related to a subtle misuse of `cljs.analyzer.api/analyze-file`.

If you the `analyze-file` function on a file as follows:
```clojure
(ns essential
  #?(:cljs (:require-macros
            [essential
              :refer
             [varialization]]))
  ;; The following line makes the difference. If this line is uncomment
  ;; the cljs.analyzer.api/analyze-file function will execute successfully
  ;; on essential.cljc
  ;; #?(:cljs (:use [cljs.core :only [coll?]]))
  )
#?(:clj
   (do
     (defmacro varialization
       [arg]
       `(var ~arg))
     ))
(defn simple []
  (varialization coll?))
```
You'll get the same error message. During the execution of `analyze-file`, the namespace `cljs.core` is unknown.

After a slack discussion with @swannodette, this is the expected behavior. To fix this, the `cljs.core` namespace have to be analyzed before run any other analysis. The handler function for this purpose is `cljs.compiler.api/with-core-cljs`.

Fixed by the new analyzer, in https://github.com/cljdoc/cljdoc-analyzer/pull/19

**Closed** 2020-04-27 09:22 UTC
Labels: Analysis, Bug

**Comment by frozar** [comment] 2020-04-27 23:34
Really glad to see this one closed :smiley:
