### ISSUE TITLE
No Namespaces found for Tupelo Clojure lib?

### ISSUE THREAD

**Issue by cloojure** [cljdoc/cljdoc#267] opened 2019-02-06 20:17 UTC
Hi - I am the maintainer of the Tupelo Clojure lib:    https://github.com/cloojure/tupelo

I just looked it up on cljdoc.org and it says "No Namespaces Found".  This is a pretty standard lein project.  Is there something preventing indexing?

Thanks,
Alan

**Comment by martinklepsch** [comment] 2019-02-07 12:07
Hi Alan, 

I kicked of another build for tupelo which you can find here: https://cljdoc.org/builds/10048. The API analysis logs can be found [on CircleCI](https://circleci.com/gh/cljdoc/builder/1459).

Analysis for Clojure is working fine but there are some issues with ClojureScript which I'll just copy here for posterity:

<details>
<pre>
Exception in thread "main" clojure.lang.ExceptionInfo: Could not analyze tupelo/math.cljc {}
	at cljdoc.analysis.impl$codox_config$ex_handler__969.invoke(impl.clj:21)
	at codox.reader.clojurescript$read_file.invokeStatic(clojurescript.clj:95)
	at codox.reader.clojurescript$read_file.invoke(clojurescript.clj:83)
	at codox.reader.clojurescript$read_namespaces$fn__863$file_reader__864.invoke(clojurescript.clj:133)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core$reduce1.invokeStatic(core.clj:944)
	at clojure.core$reduce1.invokeStatic(core.clj:934)
	at clojure.core$merge.invokeStatic(core.clj:3048)
	at clojure.core$merge.doInvoke(core.clj:3041)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at codox.reader.clojurescript$read_namespaces$fn__863.invoke(clojurescript.clj:136)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$mapcat.invokeStatic(core.clj:2783)
	at clojure.core$mapcat.doInvoke(core.clj:2783)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at codox.reader.clojurescript$read_namespaces.invokeStatic(clojurescript.clj:131)
	at codox.reader.clojurescript$read_namespaces.invoke(clojurescript.clj:105)
	at codox.main$read_namespaces.invokeStatic(main.clj:65)
	at codox.main$read_namespaces.invoke(main.clj:62)
	at codox.main$generate_docs.invokeStatic(main.clj:105)
	at codox.main$generate_docs.invoke(main.clj:98)
	at cljdoc.analysis.impl$codox_namespaces.invokeStatic(impl.clj:50)
	at cljdoc.analysis.impl$codox_namespaces.invoke(impl.clj:43)
	at cljdoc.analysis.impl$_main.invokeStatic(impl.clj:60)
	at cljdoc.analysis.impl$_main.invoke(impl.clj:57)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: nth not supported on this type: Symbol at line 1 /tmp/cljdoc-tupelo-tupelo-0.9.1262522266838784721233/jar-contents/tupelo/math.cljc {:file #object[java.io.File 0x4f8ad451 "/tmp/cljdoc-tupelo-tupelo-0.9.1262522266838784721233/jar-contents/tupelo/math.cljc"], :line 1, :column 1, :tag :cljs/analysis-error}
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:718)
	at cljs.analyzer$error.invoke(analyzer.cljc:714)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3604)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3603)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3629)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3607)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3810)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3807)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3860)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3851)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3880)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3863)
	at cljs.analyzer$parse_ns$fn__2609$fn__2613.invoke(analyzer.cljc:4042)
	at cljs.analyzer$parse_ns$fn__2609.invoke(analyzer.cljc:4042)
	at cljs.analyzer$parse_ns.invokeStatic(analyzer.cljc:4007)
	at cljs.analyzer$parse_ns.invoke(analyzer.cljc:3986)
	at cljs.analyzer.api$parse_ns.invokeStatic(api.cljc:119)
	at cljs.analyzer.api$parse_ns.invoke(api.cljc:98)
	at cljs.analyzer.api$parse_ns.invokeStatic(api.cljc:111)
	at cljs.analyzer.api$parse_ns.invoke(api.cljc:98)
	at cljs.analyzer.api$parse_ns.invokeStatic(api.cljc:108)
	at cljs.analyzer.api$parse_ns.invoke(api.cljc:98)
	at codox.reader.clojurescript$read_file.invokeStatic(clojurescript.clj:86)
	... 46 more
Caused by: java.lang.UnsupportedOperationException: nth not supported on this type: Symbol
	at clojure.lang.RT.nthFrom(RT.java:987)
	at clojure.lang.RT.nth(RT.java:936)
	at cljs.analyzer$use__GT_require.invokeStatic(analyzer.cljc:2525)
	at cljs.analyzer$use__GT_require.invoke(analyzer.cljc:2525)
	at clojure.core$partial$fn__5824.invoke(core.clj:2624)
	at clojure.core$comp$fn__5792.invoke(core.clj:2569)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1788)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:660)
	at cljs.analyzer$fn__2190$fn__2200.invoke(analyzer.cljc:2837)
	at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8144.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8131.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at cljs.analyzer$fn__2190.invokeStatic(analyzer.cljc:2820)
	at cljs.analyzer$fn__2190.invoke(analyzer.cljc:2772)
	at clojure.lang.MultiFn.invoke(MultiFn.java:252)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3600)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3605)
	... 66 more
</pre>
</details>

Most important is probably this line:

```
Caused by: clojure.lang.ExceptionInfo: nth not supported on this type: Symbol at line 1 /tmp/cljdoc-tupelo-tupelo-0.9.1262522266838784721233/jar-contents/tupelo/math.cljc {:file #object[java.io.File 0x4f8ad451 "/tmp/cljdoc-tupelo-tupelo-0.9.1262522266838784721233/jar-contents/tupelo/math.cljc"], :line 1, :column 1, :tag :cljs/analysis-error}
```

If you want to experiment with this and perhaps try some changes in tupelo you can clone the cljdoc repo and run the following:
```
./script/cljdoc ingest -p tupelo -v 0.9.126
```
The version can also be only available in your local maven and the script should pick it up accordingly.

Feel free to hit me up in `#cljdoc` on Slack if you need help as well.

**Comment by martinklepsch** [comment] 2019-03-26 08:55
Looks like this has been fixed: https://cljdoc.org/d/tupelo/tupelo/0.9.138

Closing. 🎉

**Closed by martinklepsch** 2019-03-26 08:55 UTC
Labels: Analysis, Bug, Question

**Comment by cloojure** [comment] 2019-03-26 18:04
Looks good, glad its working now.
Alan
